# Numpy

# import Libraries

In [260]:
import pandas as pd
import numpy as np

# Load Dataset

In [261]:
df = pd.read_csv(r"C:\Users\polur\Desktop\Customer Churn Analysis\Dataset\Cleaned_Data\customer_churn_Cleaned_dataset.csv")
print(df)

      Unnamed: 0  customerID  gender  SeniorCitizen Partner Dependents  \
0              0  7590-VHVEG  Female              0     Yes         No   
1              1  5575-GNVDE    Male              0      No         No   
2              2  3668-QPYBK    Male              0      No         No   
3              3  7795-CFOCW    Male              0      No         No   
4              4  9237-HQITU  Female              0      No         No   
...          ...         ...     ...            ...     ...        ...   
7038        7038  6840-RESVB    Male              0     Yes        Yes   
7039        7039  2234-XADUH  Female              0     Yes        Yes   
7040        7040  4801-JZAZL  Female              0     Yes        Yes   
7041        7041  8361-LTMKD    Male              1     Yes         No   
7042        7042  3186-AJIEK    Male              0      No         No   

      tenure PhoneService     MultipleLines InternetService  ...  \
0          1           No  No phone service

In [262]:
df.head()

,Unnamed: 0,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,Total_Charges,Churn
0,0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,0
2,2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1


In [263]:
df.shape

(7043, 22)

In [264]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Unnamed: 0        7043 non-null   int64  
 1   customerID        7043 non-null   object 
 2   gender            7043 non-null   object 
 3   SeniorCitizen     7043 non-null   int64  
 4   Partner           7043 non-null   object 
 5   Dependents        7043 non-null   object 
 6   tenure            7043 non-null   int64  
 7   PhoneService      7043 non-null   object 
 8   MultipleLines     7043 non-null   object 
 9   InternetService   7043 non-null   object 
 10  OnlineSecurity    7043 non-null   object 
 11  OnlineBackup      7043 non-null   object 
 12  DeviceProtection  7043 non-null   object 
 13  TechSupport       7043 non-null   object 
 14  StreamingTV       7043 non-null   object 
 15  StreamingMovies   7043 non-null   object 
 16  Contract          7043 non-null   object 


In [265]:
df.columns

Index(['Unnamed: 0', 'customerID', 'gender', 'SeniorCitizen', 'Partner',
       'Dependents', 'tenure', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'Total_Charges',
       'Churn'],
      dtype='object')

In [266]:
df.describe()

,Unnamed: 0,SeniorCitizen,tenure,MonthlyCharges,Churn
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,3521.000000,0.162147,32.371149,64.761692,0.265370
std,2033.283305,0.368612,24.559481,30.090047,0.441561
min,0.000000,0.000000,0.000000,18.250000,0.000000
25%,1760.500000,0.000000,9.000000,35.500000,0.000000
50%,3521.000000,0.000000,29.000000,70.350000,0.000000
75%,5281.500000,0.000000,55.000000,89.850000,1.000000
max,7042.000000,1.000000,72.000000,118.750000,1.000000


# Convert The Numpy

In [267]:
df["SeniorCitizen"].to_numpy().dtype
df['tenure'].to_numpy()
df['MonthlyCharges'].to_numpy()
df['Churn'].to_numpy()

array([0, 0, 1, ..., 0, 1, 0], shape=(7043,))

In [268]:
len(df)

7043

In [269]:
np.array(df['SeniorCitizen'])

array([0, 0, 0, ..., 0, 1, 0], shape=(7043,))

In [270]:
np.array(df['MonthlyCharges'])

array([ 29.85,  56.95,  53.85, ...,  29.6 ,  74.4 , 105.65], shape=(7043,))

In [271]:
type('SeniorCitizen')

str

In [272]:

type('MonthlyCharges')

str

In [273]:
df['MonthlyCharges'].ndim

1

In [274]:
df["SeniorCitizen"].ndim


1

In [275]:
df['tenure'].ndim



1

In [276]:
df['Churn'].ndim

1

In [277]:
df['Churn'].shape

(7043,)

In [278]:
df['MonthlyCharges'].size

7043

In [279]:
df['Churn'].size

7043

In [280]:
df[['MonthlyCharges','Churn','tenure','SeniorCitizen']].size

28172

In [281]:
df['SeniorCitizen'].nbytes

56344

In [282]:
df['Churn'].nbytes

56344

In [283]:
df['MonthlyCharges'].nbytes

56344

In [284]:
df['MonthlyCharges'].T

0        29.85
1        56.95
2        53.85
3        42.30
4        70.70
         ...  
7038     84.80
7039    103.20
7040     29.60
7041     74.40
7042    105.65
Name: MonthlyCharges, Length: 7043, dtype: float64

In [285]:
df['Churn'].T

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

In [286]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [287]:
np.ones(700)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [288]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [289]:
np.full(250,10)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10

In [290]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [291]:
np.identity(15)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [292]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Range Functions

In [293]:
np.arange(555)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [294]:
np.linspace(1,250,5)

array([  1.  ,  63.25, 125.5 , 187.75, 250.  ])

In [295]:
np.logspace(1,5,3)

array([1.e+01, 1.e+03, 1.e+05])

# Random Array

In [296]:
np.random.randn(5)

array([-0.41461575,  0.94400614, -0.46235252,  0.41144833, -1.37136687])

In [297]:
np.random.randint(1,100,10)

array([52, 77, 41, 53, 50, 15,  7, 40, 28, 32], dtype=int32)

In [298]:
np.random.random(2)

array([0.29800686, 0.62547806])

In [299]:
np.random.random(100)

array([0.15485757, 0.37299984, 0.20903704, 0.69579497, 0.94420884,
       0.99551097, 0.45027681, 0.25253039, 0.44282937, 0.84726941,
       0.20600568, 0.95209565, 0.34186577, 0.98580366, 0.83860889,
       0.80857053, 0.31790467, 0.00877721, 0.38213291, 0.30180937,
       0.03739699, 0.50536526, 0.40303131, 0.63455647, 0.62118632,
       0.12074664, 0.97696555, 0.18693143, 0.44527402, 0.48811754,
       0.8130628 , 0.0992296 , 0.42864428, 0.62850217, 0.21515562,
       0.6274679 , 0.92366484, 0.99751813, 0.03245108, 0.23558823,
       0.31030712, 0.3991261 , 0.24225716, 0.20348799, 0.95455384,
       0.9185216 , 0.0469925 , 0.33881302, 0.40514855, 0.23901453,
       0.6288729 , 0.64038075, 0.85050423, 0.74086927, 0.54257333,
       0.65358677, 0.27398878, 0.59305619, 0.48922725, 0.13334447,
       0.24254428, 0.29169345, 0.92430957, 0.23038664, 0.2892439 ,
       0.36935413, 0.66374274, 0.11823839, 0.95394521, 0.86557122,
       0.57721607, 0.67403787, 0.01666047, 0.33894478, 0.79566

In [300]:
np.random.choice(10)

6

In [301]:
np.random.choice(df['Churn'])

np.int64(1)

In [302]:
np.random.choice(df['Churn'])

np.int64(0)

In [303]:

np.random.randint(df['MonthlyCharges'])

array([ 3, 30, 43, ..., 27, 20, 91], shape=(7043,), dtype=int32)

In [304]:
np.random.seed(42)

In [305]:
np.zeros(len(df), dtype=int)

array([0, 0, 0, ..., 0, 0, 0], shape=(7043,))

# Array Indexing And Slicing

In [306]:
df['MonthlyCharges'][0]

np.float64(29.85)

In [307]:
df['MonthlyCharges'][120]

np.float64(99.8)

In [308]:
df['Churn'][5]

np.int64(1)

In [309]:
df["SeniorCitizen"][15]

np.int64(0)

In [310]:
df['tenure'][500]

np.int64(34)

In [311]:
df['tenure'][100]

np.int64(1)

# Slicing

In [312]:
df["SeniorCitizen"][15:2]

Series([], Name: SeniorCitizen, dtype: int64)

In [313]:
df['MonthlyCharges'][0:15]

0      29.85
1      56.95
2      53.85
3      42.30
4      70.70
5      99.65
6      89.10
7      29.75
8     104.80
9      56.15
10     49.95
11     18.95
12    100.35
13    103.70
14    105.50
Name: MonthlyCharges, dtype: float64

In [314]:
df['tenure'][0:10]

0     1
1    34
2     2
3    45
4     2
5     8
6    22
7    10
8    28
9    62
Name: tenure, dtype: int64

In [315]:
df['Churn'][1:5]

1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

In [316]:
df[['Churn'] + ['MonthlyCharges']]

,Churn,MonthlyCharges
0,0,29.85
1,0,56.95
2,1,53.85
3,0,42.30
4,1,70.70
...,...,...
7038,0,84.80
7039,0,103.20
7040,0,29.60
7041,1,74.40


# Trigonometric Functions

In [317]:
np.sin(5)

np.float64(-0.9589242746631385)

In [318]:
np.cos(2)

np.float64(-0.4161468365471424)

In [319]:
np.tan(10)

np.float64(0.6483608274590866)

# Logarithmic

In [320]:
df.describe()

,Unnamed: 0,SeniorCitizen,tenure,MonthlyCharges,Churn
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,3521.000000,0.162147,32.371149,64.761692,0.265370
std,2033.283305,0.368612,24.559481,30.090047,0.441561
min,0.000000,0.000000,0.000000,18.250000,0.000000
25%,1760.500000,0.000000,9.000000,35.500000,0.000000
50%,3521.000000,0.000000,29.000000,70.350000,0.000000
75%,5281.500000,0.000000,55.000000,89.850000,1.000000
max,7042.000000,1.000000,72.000000,118.750000,1.000000


In [321]:
np.log10(10)

np.float64(1.0)

In [322]:
np.log(df['MonthlyCharges'])

0       3.396185
1       4.042174
2       3.986202
3       3.744787
4       4.258446
          ...   
7038    4.440296
7039    4.636669
7040    3.387774
7041    4.309456
7042    4.660132
Name: MonthlyCharges, Length: 7043, dtype: float64

In [323]:
np.exp(df['MonthlyCharges'])

0       9.197934e+12
1       5.408424e+24
2       2.436452e+23
3       2.347776e+18
4       5.065471e+30
            ...     
7038    6.732433e+36
7039    6.594631e+44
7040    7.163358e+12
7041    2.048847e+32
7042    7.642088e+45
Name: MonthlyCharges, Length: 7043, dtype: float64

In [324]:
np.exp(df['SeniorCitizen'])

0       1.000000
1       1.000000
2       1.000000
3       1.000000
4       1.000000
          ...   
7038    1.000000
7039    1.000000
7040    1.000000
7041    2.718282
7042    1.000000
Name: SeniorCitizen, Length: 7043, dtype: float64

In [325]:
np.round(df['tenure'])

0        1
1       34
2        2
3       45
4        2
        ..
7038    24
7039    72
7040    11
7041     4
7042    66
Name: tenure, Length: 7043, dtype: int64

In [326]:
df.describe()

,Unnamed: 0,SeniorCitizen,tenure,MonthlyCharges,Churn
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,3521.000000,0.162147,32.371149,64.761692,0.265370
std,2033.283305,0.368612,24.559481,30.090047,0.441561
min,0.000000,0.000000,0.000000,18.250000,0.000000
25%,1760.500000,0.000000,9.000000,35.500000,0.000000
50%,3521.000000,0.000000,29.000000,70.350000,0.000000
75%,5281.500000,0.000000,55.000000,89.850000,1.000000
max,7042.000000,1.000000,72.000000,118.750000,1.000000


In [327]:
df['MonthlyCharges'].round(25)

0        29.85
1        56.95
2        53.85
3        42.30
4        70.70
         ...  
7038     84.80
7039    103.20
7040     29.60
7041     74.40
7042    105.65
Name: MonthlyCharges, Length: 7043, dtype: float64

In [328]:
np.floor(25)

np.int64(25)

In [329]:
np.ceil(df['SeniorCitizen'])

0       0
1       0
2       0
3       0
4       0
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: SeniorCitizen, Length: 7043, dtype: int64

In [330]:
df['tenure'].round(10)

0        1
1       34
2        2
3       45
4        2
        ..
7038    24
7039    72
7040    11
7041     4
7042    66
Name: tenure, Length: 7043, dtype: int64

In [331]:
df['Churn'].round(5)

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

# Statistical Functions

In [332]:
df.describe()

,Unnamed: 0,SeniorCitizen,tenure,MonthlyCharges,Churn
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,3521.000000,0.162147,32.371149,64.761692,0.265370
std,2033.283305,0.368612,24.559481,30.090047,0.441561
min,0.000000,0.000000,0.000000,18.250000,0.000000
25%,1760.500000,0.000000,9.000000,35.500000,0.000000
50%,3521.000000,0.000000,29.000000,70.350000,0.000000
75%,5281.500000,0.000000,55.000000,89.850000,1.000000
max,7042.000000,1.000000,72.000000,118.750000,1.000000


In [333]:
df['SeniorCitizen'].count()



np.int64(7043)

In [334]:
df['SeniorCitizen'].mean()

np.float64(0.1621468124378816)

In [335]:
df['SeniorCitizen'].max()

np.int64(1)

In [336]:
df['SeniorCitizen'].min()

np.int64(0)

In [337]:
df['SeniorCitizen'].std()

np.float64(0.3686116056100131)

In [338]:
df['SeniorCitizen'].var()

np.float64(0.13587451579039184)

In [339]:
df['SeniorCitizen'].median()

np.float64(0.0)

In [340]:
np.percentile(10,10)

np.float64(10.0)

In [341]:
df['tenure'].count()

np.int64(7043)

In [342]:
df['tenure'].max()

np.int64(72)

In [343]:
df['tenure'].min()

np.int64(0)

In [344]:
df['tenure'].sum(0)

np.int64(227990)

In [345]:
df['tenure'].var()

np.float64(603.1681081237368)

In [346]:
df['tenure'].std()

np.float64(24.55948102309446)

In [347]:
df[['MonthlyCharges','Churn']].sum()

MonthlyCharges    456116.6
Churn               1869.0
dtype: float64

In [348]:
df[['MonthlyCharges','Churn']].max()

MonthlyCharges    118.75
Churn               1.00
dtype: float64

In [349]:
df[['MonthlyCharges','Churn']].min()

MonthlyCharges    18.25
Churn              0.00
dtype: float64

In [350]:
df[['MonthlyCharges','Churn']].var()

MonthlyCharges    905.410934
Churn               0.194976
dtype: float64

In [351]:
df[['MonthlyCharges','Churn']].mean()

MonthlyCharges    64.761692
Churn              0.265370
dtype: float64

In [352]:
np.average(df['SeniorCitizen'])

np.float64(0.1621468124378816)

In [353]:
np.argmax(df['Churn'])

np.int64(2)

In [354]:
np.argmin(df['tenure'])

np.int64(488)

In [355]:
np.shape(df['MonthlyCharges'])

(7043,)

In [356]:
df.shape

(7043, 22)

In [357]:
df["Churn"]

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

In [358]:
df['MonthlyCharges']

0        29.85
1        56.95
2        53.85
3        42.30
4        70.70
         ...  
7038     84.80
7039    103.20
7040     29.60
7041     74.40
7042    105.65
Name: MonthlyCharges, Length: 7043, dtype: float64

In [359]:
df[df['MonthlyCharges']>89.1]

,Unnamed: 0,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,Total_Charges,Churn
5,5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,1
8,8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,1
12,12,8091-TTVAX,Male,0,Yes,No,58,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,One year,No,Credit card (automatic),100.35,5681.1,0
13,13,0280-XJGEX,Male,0,No,No,49,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,1
14,14,5129-JLPIS,Male,0,No,No,25,Yes,No,Fiber optic,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,105.50,2686.05,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7023,7023,1035-IPQPU,Female,1,Yes,No,63,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,103.50,6479.4,0
7025,7025,2823-LKABH,Female,0,No,No,18,Yes,Yes,Fiber optic,...,Yes,Yes,No,Yes,Month-to-month,Yes,Bank transfer (automatic),95.05,1679.4,0
7034,7034,0639-TSIQW,Female,0,No,No,67,Yes,Yes,Fiber optic,...,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),102.95,6886.25,1
7039,7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,0


In [360]:
monthly = df["MonthlyCharges"].to_numpy()

In [361]:
np.where(monthly == 29.85)

(array([   0, 3139]),)

In [362]:
np.where(monthly > 100)

(array([   8,   12,   13,   14,   15,   17,   38,   57,   59,   60,   72,
          75,   83,   93,   94,  104,  106,  117,  142,  152,  171,  178,
         193,  197,  198,  200,  202,  208,  209,  230,  241,  256,  257,
         261,  264,  267,  273,  276,  297,  308,  312,  315,  325,  336,
         339,  357,  369,  377,  384,  396,  422,  426,  437,  440,  441,
         442,  445,  449,  455,  462,  464,  466,  483,  486,  490,  500,
         511,  513,  515,  520,  524,  526,  533,  540,  547,  548,  550,
         551,  560,  566,  568,  573,  574,  590,  603,  604,  608,  609,
         613,  617,  627,  628,  630,  635,  638,  675,  678,  683,  707,
         736,  737,  745,  746,  775,  778,  785,  807,  808,  810,  811,
         817,  818,  820,  822,  830,  841,  850,  855,  876,  880,  883,
         887,  889,  891,  896,  897,  903,  905,  909,  912,  919,  928,
         938,  944,  965,  975,  978, 1025, 1026, 1036, 1061, 1077, 1088,
        1090, 1093, 1103, 1118, 1125, 

In [363]:
np.where(
    (monthly >= 50) & (monthly <= 100)
)[0]

array([   1,    2,    4, ..., 7036, 7038, 7041], shape=(3847,))

In [364]:
df['MonthlyCharges']

0        29.85
1        56.95
2        53.85
3        42.30
4        70.70
         ...  
7038     84.80
7039    103.20
7040     29.60
7041     74.40
7042    105.65
Name: MonthlyCharges, Length: 7043, dtype: float64

In [365]:
df.describe()

,Unnamed: 0,SeniorCitizen,tenure,MonthlyCharges,Churn
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,3521.000000,0.162147,32.371149,64.761692,0.265370
std,2033.283305,0.368612,24.559481,30.090047,0.441561
min,0.000000,0.000000,0.000000,18.250000,0.000000
25%,1760.500000,0.000000,9.000000,35.500000,0.000000
50%,3521.000000,0.000000,29.000000,70.350000,0.000000
75%,5281.500000,0.000000,55.000000,89.850000,1.000000
max,7042.000000,1.000000,72.000000,118.750000,1.000000


# Unique & Counting

In [366]:
df['Churn'].unique()

array([0, 1])

In [367]:
np.count_nonzero(df["Churn"])

1869

In [368]:
np.bincount(df['Churn'])

array([5174, 1869])

In [369]:
df['tenure'].unique()

array([ 1, 34,  2, 45,  8, 22, 10, 28, 62, 13, 16, 58, 49, 25, 69, 52, 71,
       21, 12, 30, 47, 72, 17, 27,  5, 46, 11, 70, 63, 43, 15, 60, 18, 66,
        9,  3, 31, 50, 64, 56,  7, 42, 35, 48, 29, 65, 38, 68, 32, 55, 37,
       36, 41,  6,  4, 33, 67, 23, 57, 61, 14, 20, 53, 40, 59, 24, 44, 19,
       54, 51, 26,  0, 39])

In [370]:
df['MonthlyCharges'].unique()

array([29.85, 56.95, 53.85, ..., 63.1 , 44.2 , 78.7 ], shape=(1585,))

In [371]:
df['SeniorCitizen'].unique()

array([0, 1])

# Missing Values Function

In [372]:
np.nanmean(df['SeniorCitizen'])

np.float64(0.1621468124378816)

In [373]:
np.nanmean(df['MonthlyCharges'])

np.float64(64.76169246059918)

In [374]:
np.isnan(df["Churn"])

0       False
1       False
2       False
3       False
4       False
        ...  
7038    False
7039    False
7040    False
7041    False
7042    False
Name: Churn, Length: 7043, dtype: bool

In [375]:
np.isnan(df['MonthlyCharges'])

0       False
1       False
2       False
3       False
4       False
        ...  
7038    False
7039    False
7040    False
7041    False
7042    False
Name: MonthlyCharges, Length: 7043, dtype: bool

In [376]:
np.nanmean(df['SeniorCitizen'])

np.float64(0.1621468124378816)

In [377]:
np.nanstd(df['SeniorCitizen'])

np.float64(0.36858543603093713)

In [378]:
np.nanstd(df['Churn'])

np.float64(0.44152995647932314)

In [379]:
np.nanstd(df[['Churn','SeniorCitizen']])

np.float64(0.40995818445965493)